name: Rust

on:
  push:
    branches: [ v2 ]
  pull_request:
    branches: [ v2 ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Fetch submodule(s)
      run: git submodule update --init --recursive
    - name: Install 5dchess-notation dependencies
      run: |
        cd 5dchess-notation
        npm i
        cd ..
    - name: Prepare tests
      run: ./prepare-tests.sh
    - name: Run tests
      run: cargo test --verbose --release
