name: Rust

on:
  push:
    branches: [ v2 ]
  pull_request:
    branches: [ v2 ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Prepare tests
      run: ./prepare-tests.sh
    - name: Run tests
      run: cargo test --verbose --release
